language: node_js

node_js:
  - 8
  - 7
cache: yarn

deploy:
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard 
  keep-history: true
  on:
    branch: master