language: node_js

node_js:
  - 8
  - 7

script: yarn run deploy
deploy:
  local-dir: ./build
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard 
  keep-history: false
  on:
    branch: master